# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - r: oldrel
      dist: xenial
    - r: release
      dist: xenial
    - r: devel
      dist: xenial
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: osx
      r: devel

cache: packages
